# Generated by Django 4.2.4 on 2023-10-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmod',
            name='people_rest',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='people_rest',
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='cmo_conditioning_afternoon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='CMO Acondicionado Tarde'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='cmo_conditioning_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='CMO Acondicionado Noche'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_conditioning_absence',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Inasistencia'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_conditioning_afternoon',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Tarde'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_conditioning_afternoon_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Acondicionado Tarde'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_conditioning_night',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Noche'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_conditioning_night_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Acondicionado Noche'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_conditioning_rest',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Descanso'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_packing_absence',
            field=models.IntegerField(default=0, verbose_name='Personas Envasado Inasistencia'),
        ),
        migrations.AddField(
            model_name='historicalmod',
            name='people_packing_rest',
            field=models.IntegerField(default=0, verbose_name='Personas Envasado Descanso'),
        ),
        migrations.AddField(
            model_name='mod',
            name='cmo_conditioning_afternoon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='CMO Acondicionado Tarde'),
        ),
        migrations.AddField(
            model_name='mod',
            name='cmo_conditioning_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='CMO Acondicionado Noche'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_conditioning_absence',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Inasistencia'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_conditioning_afternoon',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Tarde'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_conditioning_afternoon_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Acondicionado Tarde'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_conditioning_night',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Noche'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_conditioning_night_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Acondicionado Noche'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_conditioning_rest',
            field=models.IntegerField(default=0, verbose_name='Personas Acondicionado Descanso'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_packing_absence',
            field=models.IntegerField(default=0, verbose_name='Personas Envasado Inasistencia'),
        ),
        migrations.AddField(
            model_name='mod',
            name='people_packing_rest',
            field=models.IntegerField(default=0, verbose_name='Personas Envasado Descanso'),
        ),
    ]
