# Generated by Django 4.1.7 on 2023-12-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsamples',
            name='tracking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking'),
        ),
        migrations.AddField(
            model_name='samples',
            name='tracking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking'),
        ),
        migrations.AlterField(
            model_name='historicalsamples',
            name='status',
            field=models.CharField(choices=[('A', 'Solicitud recepcionada y validada'), ('DP', 'Entrega producción/calidad'), ('WD', 'Entrega almacén'), ('ST', 'Enviado a Tarma'), ('RL', 'Recibido en Lima'), ('SC', 'Programar courier'), ('STC', 'Enviado al cliente'), ('ND', 'No entregado'), ('R', 'Devolución'), ('C', 'Cancelado')], default='A', max_length=19, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='status',
            field=models.CharField(choices=[('A', 'Solicitud recepcionada y validada'), ('DP', 'Entrega producción/calidad'), ('WD', 'Entrega almacén'), ('ST', 'Enviado a Tarma'), ('RL', 'Recibido en Lima'), ('SC', 'Programar courier'), ('STC', 'Enviado al cliente'), ('ND', 'No entregado'), ('R', 'Devolución'), ('C', 'Cancelado')], default='A', max_length=19, verbose_name='Estado'),
        ),
    ]
