# Generated by Django 4.1.7 on 2023-12-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_historicalsamples_tracking_samples_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsamples',
            name='drive',
            field=models.URLField(blank=True, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='samples',
            name='drive',
            field=models.URLField(blank=True, null=True, verbose_name='Código'),
        ),
    ]
