/*AUTHENTICATION*/
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


/*COLLECTION*/

export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_PARCELS_FAIL = 'GET_PARCELS_FAIL';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';

export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';

export const UPDATE_PARCEL_SUCCESS = 'UPDATE_PARCEL_SUCCESS';
export const UPDATE_PARCEL_FAIL = 'UPDATE_PARCEL_FAIL';

export const ADD_PARCEL_SUCCESS = 'ADD_PARCEL_SUCCESS';
export const ADD_PARCEL_FAIL = 'ADD_PARCEL_FAIL';

export const GET_PROVIDERS_CATEGORY_SUCCESS = 'GET_PROVIDERS_CATEGORY_SUCCESS';
export const GET_PROVIDERS_CATEGORY_FAIL = 'GET_PROVIDERS_CATEGORY_FAIL';



//Management

export const LOADING_MANAGEMENT_SUCCESS = 'LOADING_MANAGEMENT_SUCCESS';
export const LOADING_MANAGEMENT_FAIL = 'LOADING_MANAGEMENT_FAIL';


export const GET_SUPPLIERS_RM_SUCCESS = 'GET_SUPPLIERS_RM_SUCCESS';
export const GET_SUPPLIERS_RM_FAIL = 'GET_SUPPLIER_RM_FAIL';

export const GET_SUPPLIER_RM_SUCCESS = 'GET_SUPPLIER_RM_SUCCESS';
export const GET_SUPPLIER_RM_FAIL = 'GET_SUPPLIER_RM_FAIL'


export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL'

export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL'

export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_FAIL = 'GET_SUPPLIERS_FAIL'

export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_FAIL = 'GET_SUPPLIER_FAIL'

export const GET_OUTSOURCINGS_SUCCESS = 'GET_OUTSOURCINGS_SUCCESS';
export const GET_OUTSOURCINGS_FAIL = 'GET_OUTSOURCINGS_FAIL'

export const GET_OUTSOURCING_SUCCESS = 'GET_OUTSOURCING_SUCCESS';
export const GET_OUTSOURCING_FAIL = 'GET_OUTSOURCING_FAIL'

export const GET_TRANSPORTS_SUCCESS = 'GET_TRANSPORTS_SUCCESS';
export const GET_TRANSPORTS_FAIL = 'GET_TRANSPORTS_FAIL'

export const GET_TRANSPORT_SUCCESS = 'GET_TRANSPORT_SUCCESS';
export const GET_TRANSPORT_FAIL = 'GET_TRANSPORT_FAIL'
export const GET_STORAGE_AREAS_SUCCESS = 'GET_STORAGE_AREAS_SUCCESS';
export const GET_STORAGE_AREAS_FAIL = 'GET_STORAGE_AREAS_FAIL'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL'
export const GET_COSTS_PRODUCTION_SUCCESS = 'GET_COSTS_PRODUCTION_SUCCESS';
export const GET_COSTS_PRODUCTION_FAIL = 'GET_COSTS_PRODUCTION_FAIL'
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS';
export const GET_UNITS_FAIL = 'GET_UNITS_FAIL'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'


/*LOGISTIC*/

export const UPDATE_LOT_SUCCESS = 'UPDATE_LOT_SUCCESS';
export const UPDATE_LOT_FAIL = 'UPDATE_LOT_FAIL';
export const GET_LOTS_STOCK_SUCCESS = 'GET_LOTS_STOCK_SUCCESS';
export const GET_LOTS_STOCK_FAIL = 'GET_LOTS_STOCK_FAIL';
export const GET_LOTS_SUCCESS = 'GET_LOTS_SUCCESS';
export const GET_LOTS_FAIL = 'GET_LOTS_FAIL';

export const GET_LOT_SUCCESS = 'GET_LOT_SUCCESS';
export const GET_LOT_FAIL = 'GET_LOT_FAIL';

export const GET_PALLETS_SUCCESS = 'GET_PALLETS_SUCCESS';
export const GET_PALLETS_FAIL = 'GET_PALLETS_FAIL';

export const ADD_DATA_LOT_SUCCESS = 'ADD_DATA_LOT_SUCCESS';
export const ADD_DATA_LOT_FAIL = 'ADD_DATA_LOT_FAIL';

export const UPDATE_DATA_LOT_SUCCESS = 'UPDATE_DATA_LOT_SUCCESS';
export const UPDATE_DATA_LOT_FAIL = 'UPDATE_DATA_LOT_FAIL';

export const DELETE_DATA_LOT_SUCCESS = 'DELETE_DATA_LOT_SUCCESS';
export const DELETE_DATA_LOT_FAIL = 'DELETE_DATA_LOT_FAIL';

export const GET_DATA_LOT_SUCCESS = 'GET_DATA_LOT_SUCCESS';
export const GET_DATA_LOT_FAIL = 'GET_DATA_LOT_FAIL';

export const ADD_STOCK_LOT_SUCCESS = 'ADD_STOCK_LOT_SUCCESS';
export const ADD_STOCK_LOT_FAIL = 'ADD_STOCK_LOT_FAIL';

export const GET_STOCK_LOT_SUCCESS = 'GET_STOCK_LOT_SUCCESS';
export const GET_STOCK_LOT_FAIL = 'GET_STOCK_LOT_FAIL';

export const DELETE_STOCK_LOT_SUCCESS = 'DELETE_STOCK_LOT_SUCCESS';
export const DELETE_STOCK_LOT_FAIL = 'DELETE_STOCK_LOT_FAIL';


export const GET_MOTION_BOXES_SUCCESS = 'GET_MOTION_BOXES_SUCCESS';
export const GET_MOTION_BOXES_FAIL = 'GET_MOTION_BOXES_FAIL';

export const ADD_MOTION_BOX_SUCCESS = 'ADD_MOTION_BOX_SUCCESS';
export const ADD_MOTION_BOX_FAIL = 'ADD_MOTION_BOX_FAIL';

export const DELETE_MOTION_BOX_SUCCESS = 'DELETE_MOTION_BOX_SUCCESS';
export const DELETE_MOTION_BOX_FAIL = 'DELETE_MOTION_BOX_FAIL';


export const ADD_LOT_SUCCESS = 'ADD_LOT_SUCCESS';
export const ADD_LOT_FAIL = 'ADD_LOT_FAIL';


export const GET_OUTPUT_ITEMS_SUCCESS = 'GET_OUTPUT_ITEMS_SUCCESS';
export const GET_OUTPUT_ITEMS_FAIL = 'GET_OUTPUT_ITEMS_FAIL';

export const ADD_OUTPUT_ITEM_SUCCESS = 'ADD_OUTPUT_ITEM_SUCCESS';
export const ADD_OUTPUT_ITEM_FAIL = 'ADD_OUTPUT_ITEM_FAIL';


/*QUALITY ASSURANCE*/
export const GET_ANALYSIS_SUCCESS = 'GET_ANALYSIS_SUCCESS';
export const GET_ANALYSIS_FAIL = 'GET_ANALYSIS_FAIL';

export const UPDATE_ANALYSIS_SUCCESS = 'UPDATE_ANALYSIS_SUCCESS';
export const UPDATE_ANALYSIS_FAIL = 'UPDATE_ANALYSIS_FAIL';

/*SALES*/
export const GET_SAMPLES_SUCCESS = 'GET_SAMPLES_SUCCESS';
export const GET_SAMPLES_FAIL = 'GET_SAMPLES_FAIL';

export const ADD_SAMPLE_SUCCESS = 'ADD_SAMPLE_SUCCESS';
export const ADD_SAMPLE_FAIL = 'ADD_SAMPLE_FAIL';

export const UPDATE_SAMPLE_SUCCESS = 'UPDATE_SAMPLE_SUCCESS';
export const UPDATE_SAMPLE_FAIL = 'UPDATE_SAMPLE_FAIL';

export const GET_CALENDAR_SAMPLES_SUCCESS = 'GET_CALENDAR_SAMPLES_SUCCESS';
export const GET_CALENDAR_SAMPLES_FAIL = 'GET_CALENDAR_SAMPLES_FAIL';


// OPERATIONS

export const GET_RECORDS_MP_SUCCESS = 'GET_RECORDS_MP_SUCCESS';
export const GET_RECORDS_MP_FAIL = 'GET_RECORDS_MP_FAIL';

export const LOADING_RECORDS_MP_SUCCESS = 'LOADING_RECORDS_MP_SUCCESS';
export const LOADING_RECORDS_MP_FAIL = 'LOADING_RECORDS_MP_FAIL';


<<<<<<< HEAD
=======
export const LOADING_MATERIALS_PRODUCTS_SUCCESS = 'LOADING_MATERIALS_PRODUCTS_SUCCESS';
export const LOADING_MATERIALS_PRODUCTS_FAIL = 'LOADING_MATERIALS_PRODUCTS_FAIL';
>>>>>>> dfddcd8ad380cc5d989c2b899a9b83231f76d977
export const GET_MATERIALS_SUCCESS = 'GET_MATERIALS_SUCCESS';
export const GET_MATERIALS_FAIL = 'GET_MATERIALS_FAIL';


export const GET_SKUS_SUCCESS = 'GET_SKUS_SUCCESS';
export const GET_SKUS_FAIL = 'GET_SKUS_FAIL';
export const GET_SKU_SUCCESS = 'GET_SKU_SUCCESS';
export const GET_SKU_FAIL = 'GET_SKU_FAIL';


export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS';
export const GET_STOCKS_FAIL = 'GET_STOCKS_FAIL';

export const GET_STOCK_ENTRIES_SUCCESS = 'GET_STOCK_ENTRIES_SUCCESS';
export const GET_STOCK_ENTRIES_FAIL = 'GET_STOCK_ENTRIES_FAIL';

export const GET_STOCK_REENTRIES_SUCCESS = 'GET_STOCK_REENTRIES_SUCCESS';
export const GET_STOCK_REENTRIES_FAIL = 'GET_STOCK_REENTRIES_FAIL';

export const GET_STOCK_OUTPUTS_SUCCESS = 'GET_STOCK_OUTPUTS_SUCCESS';
export const GET_STOCK_OUTPUTS_FAIL = 'GET_STOCK_OUTPUTS_FAIL';


<<<<<<< HEAD
=======
export const GET_STOCK_AVAILABLE_SUCCESS = 'GET_STOCK_AVAILABLE_SUCCESS';
export const GET_STOCK_AVAILABLE_FAIL = 'GET_STOCK_AVAILABLE_FAIL';


export const LOADING_STOCK_SUCCESS = 'LOADING_STOCK_SUCCESS';
export const LOADING_STOCK_FAIL = 'LOADING_STOCK_FAIL';
>>>>>>> dfddcd8ad380cc5d989c2b899a9b83231f76d977


export const GET_SALES_PLANNING_SUCCESS = 'GET_SALES_PLANNING_SUCCESS';
export const GET_SALES_PLANNING_FAIL = 'GET_SALES_PLANNING_FAIL';

export const ADD_SCHEDULE_MANUFACTURING_SUCCESS = 'ADD_SCHEDULE_MANUFACTURING_SUCCESS';
export const ADD_SCHEDULE_MANUFACTURING_FAIL = 'ADD_SCHEDULE_MANUFACTURING_FAIL';

export const UPDATE_SCHEDULE_MANUFACTURING_SUCCESS = 'UPDATE_SCHEDULE_MANUFACTURING_SUCCESS';
export const UPDATE_SCHEDULE_MANUFACTURING_FAIL = 'UPDATE_SCHEDULE_MANUFACTURING_FAIL';

export const DELETE_SCHEDULE_MANUFACTURING_SUCCESS = 'DELETE_SCHEDULE_MANUFACTURING_SUCCESS';
export const DELETE_SCHEDULE_MANUFACTURING_FAIL = 'DELETE_SCHEDULE_MANUFACTURING_FAIL';

export const GET_SCHEDULE_CALENDAR_SUCCESS = 'GET_SCHEDULE_CALENDAR_SUCCESS';
export const GET_SCHEDULE_CALENDAR_FAIL = 'GET_SCHEDULE_CALENDAR_FAIL';

// PRODUCTION

export const GET_CONDITIONING_PINEAPPLE_SUCCESS = 'GET_CONDITIONING_PINEAPPLE_SUCCESS';
export const GET_CONDITIONING_PINEAPPLE_FAIL = 'GET_CONDITIONING_PINEAPPLE_FAIL';

export const GET_PACKING_PINEAPPLE_SUCCESS = 'GET_PACKING_PINEAPPLE_SUCCESS';
export const GET_PACKING_PINEAPPLE_FAIL = 'GET_PACKING_PINEAPPLE_FAIL';

export const GET_MOD_SUCCESS = 'GET_MOD_SUCCESS';
export const GET_MOD_FAIL = 'GET_MOD_FAIL';

export const GET_OVENS_SUCCESS = 'GET_OVENS_SUCCESS';
export const GET_OVENS_FAIL = 'GET_OVENS_FAIL';


// COMMERCIAL
export const GET_SALES_PROGRESS_SUCCESS = 'GET_SALES_PROGRESS_SUCCESS';
export const GET_SALES_PROGRESS_FAIL = 'GET_SALES_PROGRESS_FAIL';

export const GET_SALE_ORDER_SUCCESS = 'GET_SALE_ORDER_SUCCESS';
export const GET_SALE_ORDER_FAIL = 'GET_SALE_ORDER_FAIL';


