# Generated by Django 4.1.7 on 2023-12-05 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('sap', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código SAP')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Precio')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_group', to='management.categories', verbose_name='Grupo de producto')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='management.unitofmeasurement', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('sap', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código SAP')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='% Rendimiento')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_group', to='management.categories', verbose_name='Grupo de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de orden de compra')),
                ('po_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de orden de compra')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad de ingreso')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio unitario')),
                ('stock', models.IntegerField(default=0, editable=False, verbose_name='Cantidad de stock')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='operations_and_planning.material', verbose_name='Material')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='management.suppliers', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Ingreso de stock',
                'verbose_name_plural': 'Ingresos de stock',
                'ordering': ('-arrival_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockReentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de reingreso')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reentries', to='operations_and_planning.stockentry')),
            ],
            options={
                'verbose_name': 'Reingreso de stock',
                'verbose_name_plural': 'Reingresos de stock',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de salida')),
                ('area', models.CharField(choices=[('P', 'Producción'), ('C', 'Calidad'), ('ID', 'I+D'), ('PP', 'PP')], default='P', max_length=2, verbose_name='Área')),
                ('applicant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Solicitante')),
                ('vale_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de vale o guía')),
                ('lot_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de lote')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_exits', to='operations_and_planning.stockentry')),
            ],
            options={
                'verbose_name': 'Salida de stock',
                'verbose_name_plural': 'Salidas de stock',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_materials', to='operations_and_planning.material', verbose_name='Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_products', to='operations_and_planning.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Recetario',
                'verbose_name_plural': 'Recetario',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('raw_material', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Materia Prima')),
                ('performance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Rendimiento')),
                ('expected', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad esperada')),
                ('stock_start', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Stock inicial')),
                ('stock_end', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Stock final')),
                ('process_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_planning_process_plant', to='management.outsourcing', verbose_name='Planta de proceso')),
            ],
            options={
                'verbose_name': 'Planificación de producción',
                'verbose_name_plural': 'Planificación de producción',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(related_name='products_recipes', through='operations_and_planning.Recipe', to='operations_and_planning.material', verbose_name='Recetario'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='management.unitofmeasurement', verbose_name='Unidad de medida'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Cantidad de stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='operations_and_planning.material')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'unique_together': {('date', 'product')},
            },
        ),
    ]
