# Generated by Django 4.2.4 on 2023-10-02 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sap', models.CharField(max_length=10, verbose_name='Código SAP')),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad mínima de pedido')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Precio')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_group', to='management.categories', verbose_name='Grupo de producto')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='management.unitofmeasurement', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('performance', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='% Rendimiento')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_group', to='management.categories', verbose_name='Grupo de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=15, verbose_name='ID del pedido')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la orden')),
                ('invoice_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='ID de la factura')),
                ('guide_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de guía')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('comment', models.TextField(blank=True, verbose_name='Información adicional')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibido')], default='pending', max_length=20, verbose_name='Estado')),
                ('drive', models.URLField(blank=True, verbose_name='Drive URL')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_currency', to='management.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Precio total')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_material', to='operations_and_planning.material', verbose_name='Material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_purchase', to='operations_and_planning.purchase', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'Artículo de compra',
                'verbose_name_plural': 'Artículos de compra',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de ingreso')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio unitario')),
                ('stock', models.IntegerField(verbose_name='Cantidad de stock')),
                ('purchase_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry', to='operations_and_planning.purchaseitems')),
            ],
            options={
                'verbose_name': 'Ingreso de stock',
                'verbose_name_plural': 'Ingresos de stock',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockReEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de reingreso')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reentries', to='operations_and_planning.stockentry')),
            ],
            options={
                'verbose_name': 'Reingreso de stock',
                'verbose_name_plural': 'Reingresos de stock',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('quantity', models.IntegerField(verbose_name='Cantidad de salida')),
                ('guide_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de guía')),
                ('vale_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de vale')),
                ('lot_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de lote')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_exits', to='operations_and_planning.stockentry')),
            ],
            options={
                'verbose_name': 'Salida de stock',
                'verbose_name_plural': 'Salidas de stock',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, verbose_name='Mes')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
                ('order_id', models.CharField(max_length=15, verbose_name='Orden de compra')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la orden')),
                ('quote_id', models.CharField(max_length=15, verbose_name='Proforma Invoice')),
                ('full_container_load_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre del contenedor')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cantidad')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio unitario')),
                ('market', models.CharField(choices=[('national', 'Nacional'), ('international', 'Internacional')], default='national', max_length=13, verbose_name='Mercado')),
                ('raw_material', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Materia Prima')),
                ('performance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Rendimiento')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Capacidad')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='Tiempo estimado de salida')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Tiempo estimado de llegada')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Precio total')),
                ('management', models.CharField(choices=[('30', '30 %'), ('60', '60 %'), ('90', '90 %'), ('100', '100 %')], default='30', max_length=3, verbose_name='Gestión')),
                ('delivery', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Enviado')], default='pending', max_length=9, verbose_name='Estado')),
                ('drive', models.URLField(blank=True, verbose_name='Drive URL')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_currency', to='management.currency', verbose_name='Moneda')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_customer', to='management.customer', verbose_name='Cliente')),
                ('process_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_process_plant', to='management.outsourcing', verbose_name='Planta de proceso')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_sku', to='operations_and_planning.product', verbose_name='SKU')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_tax', to='management.taxrates', verbose_name='Impuesto')),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Ordenes de venta',
                'ordering': ['-month', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_materials', to='operations_and_planning.material', verbose_name='Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_products', to='operations_and_planning.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Recetario',
                'verbose_name_plural': 'Recetario',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(related_name='purchases_items', through='operations_and_planning.PurchaseItems', to='operations_and_planning.material'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_supplier', to='management.suppliers', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_tax', to='management.taxrates', verbose_name='Impuesto'),
        ),
        migrations.CreateModel(
            name='ProductionPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('raw_material', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Materia Prima')),
                ('performance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Rendimiento')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Capacidad')),
                ('expected', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad esperada')),
                ('stock_start', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Stock inicial')),
                ('stock_end', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Stock final')),
                ('process_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_planning_process_plant', to='management.outsourcing', verbose_name='Planta de proceso')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_planning_sale', to='operations_and_planning.salesorder', verbose_name='Orden de venta')),
            ],
            options={
                'verbose_name': 'Planificación de producción',
                'verbose_name_plural': 'Planificación de producción',
                'ordering': ['-sale__year', '-sale__month'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(related_name='products_recipes', through='operations_and_planning.Recipe', to='operations_and_planning.material', verbose_name='Recetario'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_unit', to='management.unitofmeasurement', verbose_name='Unidad de medida'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Cantidad de stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='operations_and_planning.material')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'unique_together': {('date', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('order_id', 'supplier')},
        ),
    ]
