# Generated by Django 4.1.7 on 2023-12-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('operations_and_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplanning',
            options={'ordering': ['-sale__date'], 'verbose_name': 'Planificación de producción', 'verbose_name_plural': 'Planificación de producción'},
        ),
        migrations.AddField(
            model_name='productionplanning',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_planning', to='commercial.salesprogress', verbose_name='Orden de venta'),
        ),
    ]
