# Generated by Django 4.1.7 on 2023-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_and_planning', '0002_alter_productionplanning_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sap',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código SAP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sap',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código SAP'),
        ),
    ]
