# Generated by Django 4.2.4 on 2023-10-04 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_web_historicalcustomer_web_and_more'),
        ('operations_and_planning', '0002_product_sap'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseitems',
            name='material',
        ),
        migrations.RemoveField(
            model_name='purchaseitems',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='process_plant',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tax_rate',
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ('-arrival_date', '-id'), 'verbose_name': 'Ingreso de stock', 'verbose_name_plural': 'Ingresos de stock'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='purchase_item',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de llegada'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='operations_and_planning.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de orden de compra'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de orden de compra'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='management.suppliers', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad de ingreso'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad de stock'),
        ),
        migrations.DeleteModel(
            name='ProductionPlanning',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItems',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
