# Generated by Django 4.1.7 on 2023-12-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_and_planning', '0003_alter_material_sap_alter_product_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='performance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='% Rendimiento'),
        ),
    ]
