# Generated by Django 4.2.4 on 2023-10-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_and_planning', '0003_alter_purchase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity_euro',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, verbose_name='Cantidad - EuroPallet'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity_loose',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, verbose_name='Cantidad - Suelto'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, verbose_name='Cantidad - StandarPallet'),
        ),
    ]
