# Generated by Django 4.2.4 on 2023-10-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_and_planning', '0004_recipe_quantity_euro_recipe_quantity_loose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='stock',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cantidad de stock'),
        ),
    ]
