# Generated by Django 4.2.4 on 2023-10-04 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_delete_condition_delete_container_delete_currency_and_more'),
        ('commercial', '0018_historicalsalesprogress_slug_salesprogress_slug'),
        ('operations_and_planning', '0005_alter_stockentry_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('raw_material', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Materia Prima')),
                ('performance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Rendimiento')),
                ('expected', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad esperada')),
                ('stock_start', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Stock inicial')),
                ('stock_end', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Stock final')),
                ('process_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_planning_process_plant', to='management.outsourcing', verbose_name='Planta de proceso')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_planning_sale', to='commercial.salesprogress', verbose_name='Orden de venta')),
            ],
            options={
                'verbose_name': 'Planificación de producción',
                'verbose_name_plural': 'Planificación de producción',
            },
        ),
    ]
