# Generated by Django 4.1.7 on 2023-12-05 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido(s)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es administrador')),
                ('area', models.CharField(choices=[('GERENCIA', 'Gerencia'), ('ADMINISTRACION', 'Administración'), ('GESTION_HUMANA', 'Gestión Humana'), ('LOGISTICA', 'Logística'), ('SEGURIDAD_INDUSTRIAL', 'Seguridad Industrial'), ('COMERCIAL', 'Comercial'), ('OPERACIONES', 'Operaciones'), ('CALIDAD', 'Calidad'), ('MANTENIMIENTO', 'Mantenimiento'), ('PRODUCCION', 'Producción'), ('SUMINISTRO_AGRICOLA', 'Suministro Agrícola'), ('PLANEAMIENTO_Y_PROYECTOS', 'Planeamiento y Proyectos')], default='GERENCIA', max_length=24, verbose_name='Área')),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Gerente_General', 'Gerente General'), ('Gerente_Administacion_Finanzas', 'Gerente Administración y Finanzas'), ('Jefe_Administracion', 'Jefe Administración'), ('Asistente_Administracion', 'Asistente Administración'), ('Asistente_Tesoreria', 'Asistente Tesorería'), ('Encargado_Logistica_Compras', 'Encargado Logística y Compras'), ('Operario_Logistica', 'Operario Logística'), ('Asistente_Compras', 'Asistente Compras'), ('Encargado_Seguridad_Industrial', 'Encargado Seguridad Industrial'), ('Agente_Seguridad_Industrial', 'Agente Seguridad Industrial'), ('Asistente_Seguridad_Industrial', 'Asistente Seguridad Industrial'), ('Gerente_Comercial', 'Gerente Comercial'), ('Jefe_Ventas_Marketing', 'Jefe Ventas y Marketing'), ('Ejecutivo_Regional', 'Ejecutivo Regional'), ('Analista_Inteligencia_Comercial', 'Analista Inteligencia Comercial'), ('Encargado_Unidad_Operaciones', 'Encargado de la Unidad de Operaciones'), ('Encargada_Calidad', 'Encargada de Calidad'), ('Supervisor_Calidad_Campo', 'Supervisor de Calidad de Campo'), ('Analista_Control_Calidad', 'Analista de Control de Calidad'), ('Encargado_Certificaciones', 'Encargado de Certificaciones'), ('Asistentes_Certificaciones', 'Asistentes de Certificaciones'), ('Operario_Gestion_Ambiental', 'Operario de Gestión Ambiental'), ('Jefe_Mantenimiento', 'Jefe de Mantenimiento'), ('Técnico_Mantenimiento', 'Técnico de Mantenimiento'), ('Operario_Mantenimiento', 'Operario de Mantenimiento'), ('Jefe_Produccion', 'Jefe de Producción'), ('Supervisor_Investigacion_Desarrollo', 'Supervisor de Investigación y Desarrollo'), ('Asistente_Investigacion_Desarrollo', 'Asistente de Investigación y Desarrollo'), ('Supervisor_Produccion', 'Supervisor de Producción'), ('Controller_Produccion', 'Controller de Producción'), ('Jefe_Planta_Norte', 'Jefe de Planta Norte'), ('Jefe_Suministro_Agricola', 'Jefe de Suministro Agrícola'), ('Supervisor_Acopio', 'Supervisor de Acopio'), ('Asistente_Acopio', 'Asistente de Acopio'), ('Jefe_Planeamiento_Proyectos', 'Jefe de Planeamiento y Proyectos'), ('Planner_Mantenimiento', 'Planner de Mantenimiento'), ('Planner_Logistica', 'Planner de Logística'), ('Planner_Produccion', 'Planner de Producción'), ('Oficial_Jr_TI', 'Oficial Jr. de TI'), ('Analitico_Data', 'Analítico de Data')], default='Director', max_length=255, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido(s)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es administrador')),
                ('area', models.CharField(choices=[('GERENCIA', 'Gerencia'), ('ADMINISTRACION', 'Administración'), ('GESTION_HUMANA', 'Gestión Humana'), ('LOGISTICA', 'Logística'), ('SEGURIDAD_INDUSTRIAL', 'Seguridad Industrial'), ('COMERCIAL', 'Comercial'), ('OPERACIONES', 'Operaciones'), ('CALIDAD', 'Calidad'), ('MANTENIMIENTO', 'Mantenimiento'), ('PRODUCCION', 'Producción'), ('SUMINISTRO_AGRICOLA', 'Suministro Agrícola'), ('PLANEAMIENTO_Y_PROYECTOS', 'Planeamiento y Proyectos')], default='GERENCIA', max_length=24, verbose_name='Área')),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Gerente_General', 'Gerente General'), ('Gerente_Administacion_Finanzas', 'Gerente Administración y Finanzas'), ('Jefe_Administracion', 'Jefe Administración'), ('Asistente_Administracion', 'Asistente Administración'), ('Asistente_Tesoreria', 'Asistente Tesorería'), ('Encargado_Logistica_Compras', 'Encargado Logística y Compras'), ('Operario_Logistica', 'Operario Logística'), ('Asistente_Compras', 'Asistente Compras'), ('Encargado_Seguridad_Industrial', 'Encargado Seguridad Industrial'), ('Agente_Seguridad_Industrial', 'Agente Seguridad Industrial'), ('Asistente_Seguridad_Industrial', 'Asistente Seguridad Industrial'), ('Gerente_Comercial', 'Gerente Comercial'), ('Jefe_Ventas_Marketing', 'Jefe Ventas y Marketing'), ('Ejecutivo_Regional', 'Ejecutivo Regional'), ('Analista_Inteligencia_Comercial', 'Analista Inteligencia Comercial'), ('Encargado_Unidad_Operaciones', 'Encargado de la Unidad de Operaciones'), ('Encargada_Calidad', 'Encargada de Calidad'), ('Supervisor_Calidad_Campo', 'Supervisor de Calidad de Campo'), ('Analista_Control_Calidad', 'Analista de Control de Calidad'), ('Encargado_Certificaciones', 'Encargado de Certificaciones'), ('Asistentes_Certificaciones', 'Asistentes de Certificaciones'), ('Operario_Gestion_Ambiental', 'Operario de Gestión Ambiental'), ('Jefe_Mantenimiento', 'Jefe de Mantenimiento'), ('Técnico_Mantenimiento', 'Técnico de Mantenimiento'), ('Operario_Mantenimiento', 'Operario de Mantenimiento'), ('Jefe_Produccion', 'Jefe de Producción'), ('Supervisor_Investigacion_Desarrollo', 'Supervisor de Investigación y Desarrollo'), ('Asistente_Investigacion_Desarrollo', 'Asistente de Investigación y Desarrollo'), ('Supervisor_Produccion', 'Supervisor de Producción'), ('Controller_Produccion', 'Controller de Producción'), ('Jefe_Planta_Norte', 'Jefe de Planta Norte'), ('Jefe_Suministro_Agricola', 'Jefe de Suministro Agrícola'), ('Supervisor_Acopio', 'Supervisor de Acopio'), ('Asistente_Acopio', 'Asistente de Acopio'), ('Jefe_Planeamiento_Proyectos', 'Jefe de Planeamiento y Proyectos'), ('Planner_Mantenimiento', 'Planner de Mantenimiento'), ('Planner_Logistica', 'Planner de Logística'), ('Planner_Produccion', 'Planner de Producción'), ('Oficial_Jr_TI', 'Oficial Jr. de TI'), ('Analitico_Data', 'Analítico de Data')], default='Director', max_length=255, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
