# Generated by Django 4.2.4 on 2023-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostFixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Agua')),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Alquiler')),
                ('consumables', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Consumibles')),
                ('depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Depreciación')),
                ('electricity', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Electricidad')),
                ('internet', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Internet')),
                ('indirect_labor', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Mano de obra indirecta')),
                ('maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Mantenimiento')),
                ('laboratory', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Laboratorio')),
                ('supplementary', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Suplementarios')),
                ('communications', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Comunicaciones')),
            ],
            options={
                'verbose_name': 'Costos fijos',
                'verbose_name_plural': 'Costos fijos',
                'ordering': ['-date'],
            },
        ),
    ]
