# Generated by Django 4.2.4 on 2023-10-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='historicaloutsourcing',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='historicalsuppliers',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='historicaltransport',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='outsourcing',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='transport',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
    ]
