# Generated by Django 4.2.4 on 2023-10-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_web_historicalcustomer_web_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Cut',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Packing',
        ),
        migrations.DeleteModel(
            name='SubFamily',
        ),
        migrations.DeleteModel(
            name='TaxRates',
        ),
    ]
