# Generated by Django 4.2.4 on 2023-10-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_and_planning', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_status', models.CharField(choices=[('100', '100'), ('90', '90'), ('60', '60'), ('30', '30')], default='100', max_length=4, verbose_name='Estado comercial')),
                ('commercial_dispatch_date', models.DateField(verbose_name='Fecha de despacho comercial')),
                ('po_number', models.CharField(max_length=20, verbose_name='# OC')),
                ('pfi_number', models.CharField(max_length=20, verbose_name='# PFI')),
                ('client', models.CharField(max_length=255, verbose_name='Cliente')),
                ('payment_terms', models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90'), ('120', '120')], default='30', max_length=255, verbose_name='Términos de pago')),
                ('collection_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado de cobranza')),
                ('drive', models.URLField(blank=True, null=True, verbose_name='Drive')),
                ('market', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], default='N', max_length=1, verbose_name='Mercado')),
                ('region', models.CharField(choices=[('A', 'América'), ('E', 'Europa'), ('AS', 'Asia')], default='A', max_length=2, verbose_name='Región')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('port_city_destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto/Ciudad de destino')),
                ('transport_mode', models.CharField(choices=[('A', 'Aéreo'), ('S', 'Marítimo'), ('L', 'Terrestre')], default='S', max_length=4, verbose_name='Modo de transporte')),
                ('incoterm', models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW'), ('DAP', 'DAP'), ('DDP', 'DDP')], default='FOB', max_length=4, verbose_name='Incoterm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='KAM')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
            },
        ),
        migrations.CreateModel(
            name='SKU_PFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.proforma', verbose_name='Proforma')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations_and_planning.product', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'SKU Proforma',
                'verbose_name_plural': 'SKU Proformas',
            },
        ),
        migrations.AddField(
            model_name='proforma',
            name='skus',
            field=models.ManyToManyField(through='commercial.SKU_PFI', to='operations_and_planning.product', verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='# Factura')),
                ('invoice_date', models.DateField(verbose_name='Fecha de factura')),
                ('pfi_number', models.CharField(max_length=20, verbose_name='# PFI')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.proforma', verbose_name='Proforma')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProforma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('commercial_status', models.CharField(choices=[('100', '100'), ('90', '90'), ('60', '60'), ('30', '30')], default='100', max_length=4, verbose_name='Estado comercial')),
                ('commercial_dispatch_date', models.DateField(verbose_name='Fecha de despacho comercial')),
                ('po_number', models.CharField(max_length=20, verbose_name='# OC')),
                ('pfi_number', models.CharField(max_length=20, verbose_name='# PFI')),
                ('client', models.CharField(max_length=255, verbose_name='Cliente')),
                ('payment_terms', models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90'), ('120', '120')], default='30', max_length=255, verbose_name='Términos de pago')),
                ('collection_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado de cobranza')),
                ('drive', models.URLField(blank=True, null=True, verbose_name='Drive')),
                ('market', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], default='N', max_length=1, verbose_name='Mercado')),
                ('region', models.CharField(choices=[('A', 'América'), ('E', 'Europa'), ('AS', 'Asia')], default='A', max_length=2, verbose_name='Región')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('port_city_destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto/Ciudad de destino')),
                ('transport_mode', models.CharField(choices=[('A', 'Aéreo'), ('S', 'Marítimo'), ('L', 'Terrestre')], default='S', max_length=4, verbose_name='Modo de transporte')),
                ('incoterm', models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW'), ('DAP', 'DAP'), ('DDP', 'DDP')], default='FOB', max_length=4, verbose_name='Incoterm')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='KAM')),
            ],
            options={
                'verbose_name': 'historical Proforma',
                'verbose_name_plural': 'historical Proformas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
