# Generated by Django 4.2.4 on 2023-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_dispatchinfo_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchinfo',
            name='load_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de carga'),
        ),
    ]
