# Generated by Django 4.2.4 on 2023-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_alter_dispatchinfo_load_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalesprogress',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='salesprogress',
            name='drive',
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='commercial_status',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Estado comercial'),
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='market',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Modo de transporte'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='commercial_status',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Estado comercial'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='market',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mercado'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Modo de transporte'),
        ),
    ]
