# Generated by Django 4.2.4 on 2023-10-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_remove_historicalsalesprogress_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprogress',
            name='dispatch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='commercial.dispatchinfo', verbose_name='Despacho'),
        ),
    ]
