# Generated by Django 4.2.4 on 2023-10-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_salesprogress_dispatch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalesprogress',
            name='pfi_id',
        ),
        migrations.RemoveField(
            model_name='salesprogress',
            name='pfi_id',
        ),
        migrations.AddField(
            model_name='historicalsalesprogress',
            name='sku_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commercial.sku_pfi', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='salesprogress',
            name='sku_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_sales', to='commercial.sku_pfi', verbose_name='SKU'),
        ),
    ]
