# Generated by Django 4.2.4 on 2023-10-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_web_historicalcustomer_web_and_more'),
        ('commercial', '0007_historicalsalesprogress_kam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku_pfi',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalproforma',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente'),
        ),
    ]
