# Generated by Django 4.2.4 on 2023-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_sku_pfi_client_alter_historicalproforma_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesprogress',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg'),
        ),
        migrations.AddField(
            model_name='salesprogress',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg'),
        ),
    ]
