# Generated by Django 4.2.4 on 2023-10-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_alter_salesprogress_dispatch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproforma',
            name='incoterm',
            field=models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW'), ('DAP', 'DAP'), ('DDP', 'DDP'), ('CFR', 'CFR'), ('CFR_HAMBURG', 'CFR Hamburgo'), ('CFR_MIAMI', 'CFR Miami')], default='FOB', max_length=11, verbose_name='Incoterm'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='incoterm',
            field=models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW'), ('DAP', 'DAP'), ('DDP', 'DDP'), ('CFR', 'CFR'), ('CFR_HAMBURG', 'CFR Hamburgo'), ('CFR_MIAMI', 'CFR Miami')], default='FOB', max_length=11, verbose_name='Incoterm'),
        ),
    ]
