# Generated by Django 4.2.4 on 2023-10-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0011_alter_historicalproforma_incoterm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproforma',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='historicalsalesprogress',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='historicalsalesprogress',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='salesprogress',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='salesprogress',
            name='quantity',
        ),
    ]
