# Generated by Django 4.2.4 on 2023-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_remove_historicalproforma_collection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_pfi',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='$ Precio(kg)'),
        ),
    ]
