# Generated by Django 4.2.4 on 2023-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_alter_sku_pfi_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='load_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='load_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de carga'),
        ),
    ]
