# Generated by Django 4.2.4 on 2023-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_alter_historicalsalesprogress_load_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesprogress',
            name='end_process',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de proceso'),
        ),
        migrations.AddField(
            model_name='historicalsalesprogress',
            name='mp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MP'),
        ),
        migrations.AddField(
            model_name='historicalsalesprogress',
            name='start_process',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de proceso'),
        ),
        migrations.AddField(
            model_name='salesprogress',
            name='end_process',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de proceso'),
        ),
        migrations.AddField(
            model_name='salesprogress',
            name='mp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MP'),
        ),
        migrations.AddField(
            model_name='salesprogress',
            name='start_process',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de proceso'),
        ),
    ]
