# Generated by Django 4.2.4 on 2023-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0015_historicalsalesprogress_end_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesprogress',
            name='drive',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='salesprogress',
            name='drive',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Drive'),
        ),
    ]
