# Generated by Django 4.2.4 on 2023-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0016_historicalsalesprogress_drive_salesprogress_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='end_process',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fin de proceso'),
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='mp',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='MP'),
        ),
        migrations.AlterField(
            model_name='historicalsalesprogress',
            name='start_process',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Inicio de proceso'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='end_process',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fin de proceso'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='mp',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='MP'),
        ),
        migrations.AlterField(
            model_name='salesprogress',
            name='start_process',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Inicio de proceso'),
        ),
    ]
