# Generated by Django 4.2.4 on 2023-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovider',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='provider',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
    ]
